version: '3.8'

services:
  tex_getitdigital:
    image: "ghcr.io/getitdigital/texcontainer:main"
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ..:/workspace
    networks:
      get-network:

networks:
  get-network:
    name: get-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.111.0/24