name: Modul 03

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/getitdigital/texcontainer:main

    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    # Test if files in this module are changed
    - name: Configure Git Safe Directory
      run: git config --global --add safe.directory /__w/GetItDigital/GetItDigital
    - name: Get changed files in the docs folder
      id: changed-files-specific
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      with:
        files: |
          modul-03-elektrische-bauelemente/*
          Templates/*

    # Compile Skript only if files in this module are changed
    - name: compile Skript
      id: skript
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      working-directory: ./modul-03-elektrische-bauelemente
      run: latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Skript.tex
    - name: Upload Skript as artifact
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: Modul-03-Skript
        path: modul-03-elektrische-bauelemente/TeXAux/Skript.pdf
    - name: upload to Skript server
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      shell: bash
      run: |
        echo "Uploading Skript.pdf to server"
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        chmod 400 ~/.ssh/config
        ssh-add <(echo "${{secrets.SFTP_KEY}}")
        sftp -o StrictHostKeyChecking=no ${{secrets.SFTP_USERNAME}}@${{secrets.SFTP_SERVER}}:english/modul-3-elektrische-bauelemente <<< $'put modul-03-elektrische-bauelemente/TeXAux/Skript.pdf'

    # Compile Slides only if files in this module are changed
    - name: compile Folien
      id: folien
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      working-directory: ./modul-03-elektrische-bauelemente
      run: latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Folien.tex
    - name: Upload Folien as artifact
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: Modul-03-Folien
        path: modul-03-elektrische-bauelemente/TeXAux/Folien.pdf
    - name: upload to Folien server
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      shell: bash
      run: |
        echo "Uploading Folien.pdf to server"
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        chmod 400 ~/.ssh/config
        ssh-add <(echo "${{secrets.SFTP_KEY}}")
        sftp -o StrictHostKeyChecking=no ${{secrets.SFTP_USERNAME}}@${{secrets.SFTP_SERVER}}:english/modul-3-elektrische-bauelemente <<< $'put modul-03-elektrische-bauelemente/TeXAux/Folien.pdf'

    # Compile Handout only if files in this module are changed
    - name: compile Handout
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      id: handout
      working-directory: ./modul-03-elektrische-bauelemente
      run: |
        perl -pe 's/\\documentclass\[((?:(?!\]).)*)]/\\documentclass\[$1\,handout]/' Folien.tex > Handout.tex # add argument 'handout' to documentclass beamer
        latexmk -interaction=nonstopmode -file-line-error -pdf --shell-escape -outdir=TeXAux Handout.tex
    - name: Upload Handout as artifact
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: Modul-03-Handout
        path: modul-03-elektrische-bauelemente/TeXAux/Handout.pdf
    - name: upload to Handout server
      if: steps.changed-files-specific.outputs.any_changed == 'true'
      shell: bash
      run: |
        echo "Uploading Handout.pdf to server"
        which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
        mkdir -p ~/.ssh
        eval $(ssh-agent -s)
        [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        chmod 400 ~/.ssh/config
        ssh-add <(echo "${{secrets.SFTP_KEY}}")
        sftp -o StrictHostKeyChecking=no ${{secrets.SFTP_USERNAME}}@${{secrets.SFTP_SERVER}}:english/modul-3-elektrische-bauelemente <<< $'put modul-03-elektrische-bauelemente/TeXAux/Handout.pdf'
